
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class Accident
{

    public long AccidentId { get; set; }

    public long TripId { get; set; }

    public string AccidentDescription { get; set; }

    public string CaseNumber { get; set; }

    public string Comment { get; set; }

    public System.DateTime AccidentDate { get; set; }

    public string AccidentLocation { get; set; }



    public virtual Trip Trip { get; set; }

}

}
