
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class AuditTrail
{

    public int Id { get; set; }

    public System.DateTime RevisionStamp { get; set; }

    public string EntityName { get; set; }

    public long EntityKey { get; set; }

    public string UserName { get; set; }

    public string Action { get; set; }

    public string OldData { get; set; }

    public string NewData { get; set; }

    public string ChangedColumns { get; set; }

}

}
