
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class Office
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Office()
    {

        this.Drivers = new HashSet<Driver>();

        this.Users = new HashSet<User>();

    }


    public int OfficeId { get; set; }

    public string OfficeName { get; set; }

    public int OfficeTypeId { get; set; }

    public int ProvinceId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Driver> Drivers { get; set; }

    public virtual OfficeType OfficeType { get; set; }

    public virtual Province Province { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> Users { get; set; }

}

}
