
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class Report
{

    public int ReportId { get; set; }

    public int CategoryId { get; set; }

    public string ReportDescription { get; set; }

    public string ReportPath { get; set; }

    public Nullable<int> SequenceNumber { get; set; }



    public virtual Category Category { get; set; }

}

}
