
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class TripLog
{

    public long TripLogId { get; set; }

    public long TripId { get; set; }

    public string StartPoint { get; set; }

    public string EndPoint { get; set; }

    public int StartOdoMeter { get; set; }

    public int EndOdoMeter { get; set; }

    public System.DateTime TripLogDate { get; set; }



    public virtual Trip Trip { get; set; }

}

}
