
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class TripOffence
{

    public long TripOffenceId { get; set; }

    public long TripId { get; set; }

    public int OffenceTypeId { get; set; }

    public System.DateTime OffenceDate { get; set; }

    public string Comments { get; set; }



    public virtual OffenceType OffenceType { get; set; }

    public virtual Trip Trip { get; set; }

}

}
