
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class Trip
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Trip()
    {

        this.Accidents = new HashSet<Accident>();

        this.Passengers = new HashSet<Passenger>();

        this.TripLogs = new HashSet<TripLog>();

        this.TripOffences = new HashSet<TripOffence>();

    }


    public long TripId { get; set; }

    public Nullable<int> WorkflowId { get; set; }

    public string ProjectName { get; set; }

    public string TripDescription { get; set; }

    public System.DateTime TripDate { get; set; }

    public string StartPoint { get; set; }

    public string EndPoint { get; set; }

    public Nullable<int> VehicleTypeId { get; set; }

    public string AuthirisedBy { get; set; }

    public Nullable<long> VehicleId { get; set; }

    public long DriverId { get; set; }

    public Nullable<long> CoDriverId { get; set; }

    public Nullable<long> GarageCardId { get; set; }

    public Nullable<int> EndOdoMeter { get; set; }

    public System.DateTime EstimatedReturnDate { get; set; }

    public Nullable<decimal> FuelLiters { get; set; }

    public Nullable<int> StartOdoMeter { get; set; }

    public Nullable<decimal> FuelCost { get; set; }

    public string PreInspector { get; set; }

    public string PreInspectionComments { get; set; }

    public string PostInspector { get; set; }

    public string PostInspectionComments { get; set; }

    public Nullable<System.DateTime> ActualReturnDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Accident> Accidents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Passenger> Passengers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TripLog> TripLogs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TripOffence> TripOffences { get; set; }

    public virtual VehicleType VehicleType { get; set; }

    public virtual Workflow Workflow { get; set; }

    public virtual Driver Driver { get; set; }

}

}
