
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public long UserId { get; set; }

    public System.Guid AspnetUserId { get; set; }

    public string UserName { get; set; }

    public string Surname { get; set; }

    public string FirstName { get; set; }

    public string EmployeeNumber { get; set; }

    public int StatusId { get; set; }

    public string EmailAddress { get; set; }

    public string ContactNumber { get; set; }

    public int OfficeId { get; set; }



    public virtual Status Status { get; set; }

    public virtual Office Office { get; set; }

}

}
