
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class VehicleMake
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VehicleMake()
    {

        this.VehicleModels = new HashSet<VehicleModel>();

    }


    public int VehicleMakeId { get; set; }

    public string VehicleMakeName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VehicleModel> VehicleModels { get; set; }

}

}
