
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BMTemplate
{

using System;
    using System.Collections.Generic;
    
public partial class Vehicle
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vehicle()
    {

        this.GarageCards = new HashSet<GarageCard>();

        this.VehicleMaintenances = new HashSet<VehicleMaintenance>();

    }


    public long VehicleId { get; set; }

    public string RegistrationNumber { get; set; }

    public int VehicleModelId { get; set; }

    public string VINNumber { get; set; }

    public string VehicleYear { get; set; }

    public int EngineCapacityId { get; set; }

    public System.DateTime DiscRenewalDate { get; set; }

    public int ServiceInterval { get; set; }

    public int StatusId { get; set; }

    public string VehicleCondition { get; set; }

    public int SupplyTypeId { get; set; }

    public int FuelTypeId { get; set; }

    public int VehicleTypeId { get; set; }

    public int LastServiceOdoMeter { get; set; }

    public int CurrentOdoMeter { get; set; }



    public virtual EngineCapicity EngineCapicity { get; set; }

    public virtual FuelType FuelType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GarageCard> GarageCards { get; set; }

    public virtual Status Status { get; set; }

    public virtual SupplyType SupplyType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VehicleMaintenance> VehicleMaintenances { get; set; }

    public virtual VehicleModel VehicleModel { get; set; }

    public virtual VehicleType VehicleType { get; set; }

}

}
